'use client';

import React, { createContext, useContext } from 'react';
import type { Piece, Sq } from '@chess404/contracts';
import type { PieceType, CardMechanic, PieceColor } from '../types';

export interface MatchStateContextShape {
  board: (Piece | null)[][];
  turn: PieceColor;
  sel: Sq | null;
  hints: Sq[];
  lm: { from: Sq; to: Sq } | null;
  drag: Sq | null;
  dragPos: { x: number; y: number } | null;
  check: boolean;
  kingPos: Sq | null;
  over: boolean;
  winner: PieceColor | 'draw' | 'aborted' | null;
  promo: {
    row: number; col: number; color: string; fromCol?: number;
    from?: Sq; to?: Sq; moved: Set<string>;
    lm: { from: Sq; to: Sq } | null; hmc: number; fmn: number;
  } | null;
  promoPicker: { sq: Sq; options: PieceType[]; mechanic: CardMechanic } | null;
  moved: Set<string>;
  hmc: number;
  fmn: number;
  posHist: string[];
  timeW: number;
  timeB: number;
  clockActive: boolean;
  tickingState: 'white' | 'black' | null;
  fmtClock: (ms: number) => string;
  hostedRuntime: boolean | null;
  authoritativeMatchId: string | null;
  viewerSeat: 'white' | 'black' | null;
  authoritativeLive: boolean;
  authoritativeStatus: string | null;
  topSeat: 'white' | 'black';
  bottomSeat: 'white' | 'black';
  topPlayerName: string | null;
  bottomPlayerName: string | null;
  topSeatBadge: string | null;
  bottomSeatBadge: string | null;
  displayedWhiteRating: number | null;
  displayedBlackRating: number | null;
  displayedWhiteName: string | null;
  displayedBlackName: string | null;
  whiteSeatBadge: string | null;
  blackSeatBadge: string | null;
  doubleMove: any | null;
  radarActive: boolean;
  lavaSqs: any[];
  lavaExploding: Sq[];
  fogZones: any[];
  ghostPiece: { row: number; col: number; piece: Piece; ownerColor: PieceColor; roundsLeft: number } | null;
  ghostRef: React.RefObject<{ row: number; col: number; piece: Piece; ownerColor: PieceColor; roundsLeft: number } | null>;
  analysisArrows: any[];
  premove: { from: Sq; to: Sq } | null;
  isReviewing: boolean;
  reviewBoard: (Piece | null)[][] | null;
  reviewIdx: number;
  drawOffer: any | null;
  abortActive: boolean;
  abortCountdown: number | null;
  streamDisconnected: boolean;
  setSel: (sq: Sq | null) => void;
  setHints: (sqs: Sq[]) => void;
  setDrag: (d: Sq | null) => void;
  setDragPos: (p: { x: number; y: number } | null) => void;
  setBoard: (b: (Piece | null)[][]) => void;
  setOver: (o: boolean) => void;
  setWinner: React.Dispatch<React.SetStateAction<PieceColor | 'draw' | 'aborted' | null>>;
  setPremove: (p: { from: Sq; to: Sq } | null) => void;
  setDrawOffer: (offer: any | null) => void;
  setPosHist: (p: any[]) => void;
  clickSq: (r: number, c: number) => void;
  getMoves: (r: number, c: number) => Sq[];
  doMove: (fr: number, fc: number, tr: number, tc: number, forcePromo?: PieceType) => void;
  doPromo: (type: PieceType) => void;
  handlePromoPick: (type: PieceType) => void;
  cardPromo: { sq: Sq; color: PieceColor } | null;
  setCardPromo: React.Dispatch<React.SetStateAction<{ sq: Sq; color: PieceColor } | null>>;
  getCardHighlight: (row: number, col: number) => string | null;
  getDoubleMoveHighlight: (row: number, col: number) => string | null;
  toggleAnalysisArrow: (from: Sq, to: Sq) => void;
  clearAnalysisArrows: () => void;
  submitAuthoritativeIntent: (intent: any) => void;
  authoritativeActorForColor: (color: PieceColor) => { playerId: string; playerSecret?: string; playerClaimToken?: string };
  createAuthoritativeRematchRoom: () => void;
  stopAbortCountdown: () => void;
  activeFinishReasonLabel: string | null;
  authoritativeRematchBusy: boolean;
  canCreateDirectRematch: boolean;
  canQueueSameLane: boolean;
  returnToSameQueueLane: () => void;
  returnToQueueHome: () => void;
  newGame: () => void;
  finishedPrimaryActionLabel: string;
  finishedSecondaryActionLabel: string;
  boardStatusLabel: string;
  bootstrapAuthoritativeMatch: (id: string) => void;
  showHostedSoloBanner: boolean | null;
  showHostedReconnectWarning: boolean | null;
  intentInFlight: boolean;
  activeDisconnectGraceFor: string | null;
  isAttackedWithFusion: (board: (Piece | null)[][], row: number, col: number, byColor: PieceColor) => boolean;
  checkEndGame: (board: (Piece | null)[][], turn: PieceColor, moved: Set<string>, lm: { from: Sq; to: Sq } | null, hmc: number, posHist: string[], posKey: string, fen: string, opp: PieceColor) => void;
  canRespondToDrawOffer: boolean;
  hostedActionLocked: boolean;
  movHist: { n: string; w?: string; b?: string }[];
  roundNumber: number;
  chatMessages: any[];
  setChatMessages: (msgs: any[]) => void;
}

const MatchStateContext = createContext<MatchStateContextShape | null>(null);

export function useMatchState(): MatchStateContextShape {
  const ctx = useContext(MatchStateContext);
  if (!ctx) throw new Error('useMatchState must be used within MatchEngineProvider');
  return ctx;
}

export default MatchStateContext;
