'use client';

import React, { createContext, useContext } from 'react';
import type { Piece, Sq } from '@chess404/contracts';

export interface MatchEngineContextShape {
  board: (Piece | null)[][];
  turn: string;
  sel: Sq | null;
  hints: Sq[];
  lm: { from: Sq; to: Sq } | null;
  drag: { piece: Piece; from: Sq } | null;
  dragPos: { x: number; y: number } | null;
  check: boolean;
  kingPos: Record<string, Sq>;
  over: boolean;
  winner: string | null;
  topSeat: 'white' | 'black';
  bottomSeat: 'white' | 'black';
  topPlayerName: string;
  bottomPlayerName: string;
  topSeatBadge: string;
  bottomSeatBadge: string;
  displayedWhiteRating: number | null;
  displayedBlackRating: number | null;
  displayedWhiteName: string;
  displayedBlackName: string;
  whiteSeatBadge: string;
  blackSeatBadge: string;
  timeW: number;
  timeB: number;
  clockActive: boolean;
  tickingState: 'white' | 'black' | null;
  fmtClock: (ms: number) => string;
  hostedRuntime: boolean | null;
  authoritativeMatchId: string | null;
  viewerSeat: 'white' | 'black' | null;
  authoritativeLive: boolean;
  authoritativeStatus: string;
  engineOn: boolean;
  selectedCard: string | null;
  cardPending: boolean;
  whiteHand: any[];
  blackHand: any[];
  topHand: any[];
  bottomHand: any[];
  cardUsedBy: string | null;
  canUseCard: boolean;
  streamDisconnected: boolean;
  chatMessages: any[];
  movHist: string[];
  doubleMove: any | null;
  radarActive: boolean;
  setSel: (sq: Sq | null) => void;
  setHints: (sqs: Sq[]) => void;
  setDrag: (d: { piece: Piece; from: Sq } | null) => void;
  setDragPos: (p: { x: number; y: number } | null) => void;
  setBoard: (b: (Piece | null)[][]) => void;
  setOver: (o: boolean) => void;
  setWinner: (w: string | null) => void;
  clickSq: (sq: Sq) => void;
  getMoves: (sq: Sq) => Sq[];
  doMove: (from: Sq, to: Sq) => void;
  promo: boolean;
  doPromo: (p: string) => void;
  promoPicker: string[] | null;
  handlePromoPick: (p: string) => void;
  cardPromo: string | null;
  setCardPromo: (p: string | null) => void;
  getCardHighlight: (sq: Sq) => string | null;
  getDoubleMoveHighlight: (sq: Sq) => string | null;
  bombPieces: any[];
  bombExploding: string | null;
  lavaSqs: any[];
  lavaExploding: string | null;
  swapAnim: any | null;
  transformAnim: any | null;
  sniperAnim: any | null;
  teleportAnim: any | null;
  jumpAnim: any | null;
  sacrificeAnim: any | null;
  mindControlAnim: any | null;
  fuseAnim: any | null;
  fogZones: any[];
  ghostPiece: { piece: Piece; square: Sq } | null;
  ghostRef: React.RefObject<HTMLDivElement | null>;
  analysisArrows: any[];
  toggleAnalysisArrow: (from: Sq, to: Sq) => void;
  clearAnalysisArrows: () => void;
  premove: { from: Sq; to: Sq } | null;
  setPremove: (p: { from: Sq; to: Sq } | null) => void;
  isReviewing: boolean;
  reviewBoard: (Piece | null)[][] | null;
  reviewIdx: number;
  renderHand: (color: string) => React.ReactNode;
  renderPlayerCard: (color: string) => React.ReactNode;
  setChatMessages: (msgs: any[]) => void;
  submitAuthoritativeIntent: (intent: any) => void;
  authoritativeActorForColor: (color: string) => string | null;
  createAuthoritativeRematchRoom: () => void;
  hostedActionLocked: boolean;
  drawOffer: any | null;
  canRespondToDrawOffer: boolean;
  setDrawOffer: (offer: any | null) => void;
  abortActive: boolean;
  abortCountdown: number | null;
  stopAbortCountdown: () => void;
  activeFinishReasonLabel: string;
  authoritativeRematchBusy: boolean;
  canCreateDirectRematch: boolean;
  canQueueSameLane: boolean;
  returnToSameQueueLane: () => void;
  returnToQueueHome: () => void;
  newGame: () => void;
  finishedPrimaryActionLabel: string;
  finishedSecondaryActionLabel: string;
  boardStatusLabel: string;
  roundNumber: number;
  lastDrawAnim: string | null;
  soundEnabled: boolean;
  toggleSound: () => void;
  colorBlindMode: boolean;
  toggleColorBlind: () => void;
  showHostedReconnectWarning: boolean;
  intentInFlight: boolean;
  activeDisconnectGraceFor: string | null;
  bootstrapAuthoritativeMatch: (id: string) => void;
  showHostedSoloBanner: boolean;
  isAttackedWithFusion: (sq: Sq) => boolean;
  checkEndGame: () => void;
  moved: string[];
  hmc: number;
  fmn: number;
  posHist: any[];
}

const MatchEngineContext = createContext<MatchEngineContextShape | null>(null);

export function useMatchEngineContext(): MatchEngineContextShape {
  const ctx = useContext(MatchEngineContext);
  if (!ctx) throw new Error('useMatchEngineContext must be used within MatchEngineProvider');
  return ctx;
}

export default MatchEngineContext;
